[package]
name = "shared-models"
version = "0.1.0"
authors = ["Ron De Benedetti <RonDeBen@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
